"""Add FK to favorites

Revision ID: ae3647e0e042
Revises: 2745511d3676
Create Date: 2025-06-18 13:54:48.247962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3647e0e042'
down_revision = '2745511d3676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_favorites_listing_id', 'listings', ['listing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_favorites_listing_id', type_='foreignkey')
    # ### end Alembic commands ###
